# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 0, 4, 56, 525805, tzinfo=utc)),
        ),
    ]
