# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20160717_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='original_url',
            new_name='long_url',
        ),
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 18, 42, 39, 695144, tzinfo=utc)),
        ),
    ]
