# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20160717_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 18, 44, 48, 176656, tzinfo=utc)),
        ),
    ]
