# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 05:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20160718_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 5, 52, 45, 675240, tzinfo=utc)),
        ),
    ]
